### ISSUE TITLE
Git hub command

### ISSUE THREAD

**Issue by AlexDoykov** [corda/corda-docs-portal#1555]
Hello,
I think there should be a better way to change the remote when we clone the kotlin example. I think these [2 lines](https://github.com/corda/corda-docs-portal/blob/main/content/en/platform/corda/5.0/developing-applications/getting-started/installing/_index.md?plain=1#L44) should be replaced by command `git remote set-url origin <remote-url>`. The one that is currently in the example doesn't work for me.

**Comment by nadinequinr3** [comment]
Hi @AlexDoykov, Thanks for the feedback. Could you clarify please what you mean by "the example doesn't work"? Are you getting an error message? Thanks.
